name: Publish Docker Image
on: 
  push: 
    branches:
      - main
    paths: 
      - 'Dockerfile'
      - '.github/workflows/publish_docker.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.52.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
      id: bump
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.bump.outputs.new_tag }}
        release_name: ${{ steps.bump.outputs.new_tag }}
        body: |
          Changes in this Release
          - Rebuilt Docker image and published to DockerHub with new tag
        draft: false
        prerelease: false
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: tzoght/heart_disease_predictor 
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ steps.bump.outputs.new_tag }}"
